In [1]:
import polars as pl

df = pl.read_parquet("trigrams.parquet")

counts = (
    df.group_by(["word1", "word2", "word3"])
      .len()
      .rename({"len": "count"})
)

counts.head()

shape: (5, 4)
┌───────────┬─────────┬───────────┬───────┐
│ word1     ┆ word2   ┆ word3     ┆ count │
│ ---       ┆ ---     ┆ ---       ┆ ---   │
│ str       ┆ str     ┆ str       ┆ u32   │
╞═══════════╪═════════╪═══════════╪═══════╡
│ appraiser ┆ '       ┆ s         ┆ 5     │
│ his       ┆ wife    ┆ embezzled ┆ 5     │
│ guidance  ┆ for     ┆ earnings  ┆ 1     │
│ cheered   ┆ a       ┆ big       ┆ 1     │
│ iraqi     ┆ justice ┆ rather    ┆ 1     │
└───────────┴─────────┴───────────┴───────┘

In [2]:
totals = (
    counts.group_by(["word1", "word2"])
          .agg(pl.sum("count").alias("total"))
)

model = counts.join(totals, on=["word1","word2"])

model = model.with_columns(
    (pl.col("count") / pl.col("total")).alias("prob")
)

model.head()

shape: (5, 6)
┌───────────┬─────────┬───────────┬───────┬───────┬──────────┐
│ word1     ┆ word2   ┆ word3     ┆ count ┆ total ┆ prob     │
│ ---       ┆ ---     ┆ ---       ┆ ---   ┆ ---   ┆ ---      │
│ str       ┆ str     ┆ str       ┆ u32   ┆ u32   ┆ f64      │
╞═══════════╪═════════╪═══════════╪═══════╪═══════╪══════════╡
│ appraiser ┆ '       ┆ s         ┆ 5     ┆ 5     ┆ 1.0      │
│ his       ┆ wife    ┆ embezzled ┆ 5     ┆ 8132  ┆ 0.000615 │
│ guidance  ┆ for     ┆ earnings  ┆ 1     ┆ 111   ┆ 0.009009 │
│ cheered   ┆ a       ┆ big       ┆ 1     ┆ 76    ┆ 0.013158 │
│ iraqi     ┆ justice ┆ rather    ┆ 1     ┆ 22    ┆ 0.045455 │
└───────────┴─────────┴───────────┴───────┴───────┴──────────┘

In [3]:
from collections import defaultdict

lookup = defaultdict(list)

for row in model.iter_rows(named=True):
    lookup[(row["word1"], row["word2"])].append(
        (row["word3"], row["prob"])
    )

lookup[("his", "wife")]

[('embezzled', 0.0006148548942449582),
 ('completed', 0.00012297097884899163),
 ('bun', 0.00024594195769798326),
 ('hsu', 0.00012297097884899163),
 ('princess', 0.002336448598130841),
 ('iman', 0.00012297097884899163),
 ('promises', 0.00012297097884899163),
 ('martine', 0.00012297097884899163),
 ('suspecting', 0.00012297097884899163),
 ('looked', 0.00012297097884899163),
 ('ruth', 0.0006148548942449582),
 ('picked', 0.00012297097884899163),
 ('aboard', 0.00024594195769798326),
 ('sliced', 0.00012297097884899163),
 ('now', 0.00024594195769798326),
 ('contributed', 0.00012297097884899163),
 ('deng', 0.0004918839153959665),
 ('sybille', 0.00012297097884899163),
 ('home', 0.00024594195769798326),
 ('scream', 0.00024594195769798326),
 ('cover', 0.00012297097884899163),
 ('added', 0.00012297097884899163),
 ('during', 0.007009345794392523),
 ('marisol', 0.00012297097884899163),
 ('reported', 0.00012297097884899163),
 ('tried', 0.0004918839153959665),
 ('warmed', 0.00012297097884899163),
 ('having', 0.00024594195769798326),
 ('edita', 0.00012297097884899163),
 ('terri', 0.00012297097884899163),
 ('rose', 0.00012297097884899163),
 ('daw', 0.00024594195769798326),
 ('mary', 0.00024594195769798326),
 ('louise', 0.00024594195769798326),
 ('collapsed', 0.00012297097884899163),
 ('smashed', 0.00012297097884899163),
 ('went', 0.0007378258730939498),
 ('bernadette', 0.0006148548942449582),
 ('trying', 0.00024594195769798326),
 ('felt', 0.00012297097884899163),
 ('several', 0.0003689129365469749),
 ('hillary', 0.00676340383669454),
 ('commit', 0.0007378258730939498),
 ('then', 0.00012297097884899163),
 ('officially', 0.00024594195769798326),
 ('suha', 0.00012297097884899163),
 ('began', 0.0004918839153959665),
 ('monique', 0.00012297097884899163),
 ('hard', 0.00012297097884899163),
 ('rita', 0.0003689129365469749),
 ('geraldine', 0.00024594195769798326),
 ('ann', 0.0003689129365469749),
 ('suzy', 0.00012297097884899163),
 ('danielle', 0.00012297097884899163),
 ('anna', 0.00012297097884899163),
 ('tipper', 0.0004918839153959665),
 ('sally', 0.00024594195769798326),
 ('go', 0.00012297097884899163),
 ('ended', 0.00012297097884899163),
 ('sent', 0.00024594195769798326),
 ('fadwa', 0.00024594195769798326),
 ('chaz', 0.00012297097884899163),
 ('arrived', 0.002459419576979833),
 ('luciana', 0.00012297097884899163),
 ('so', 0.000983767830791933),
 ('survived', 0.0003689129365469749),
 ('wants', 0.00012297097884899163),
 ('sharon', 0.00012297097884899163),
 ('mia', 0.00012297097884899163),
 ('spied', 0.0003689129365469749),
 ('tatiana', 0.00012297097884899163),
 ('du', 0.00012297097884899163),
 ('relinquished', 0.00012297097884899163),
 ('euro11', 0.00012297097884899163),
 ('patricia', 0.00012297097884899163),
 ('rosemary', 0.00012297097884899163),
 ('potjaman', 0.0007378258730939498),
 ('firmly', 0.00012297097884899163),
 ('pauline', 0.00012297097884899163),
 ('dodged', 0.00012297097884899163),
 ('passed', 0.00012297097884899163),
 ('allegedly', 0.00012297097884899163),
 ('michelle', 0.0031972454500737825),
 ('exploited', 0.00012297097884899163),
 ('called', 0.00024594195769798326),
 ('runs', 0.00024594195769798326),
 ('francesca', 0.00012297097884899163),
 ('[', 0.004181013280865716),
 ('want', 0.00012297097884899163),
 ('something', 0.00012297097884899163),
 ('caved', 0.00024594195769798326),
 ('rosalia', 0.00012297097884899163),
 ('evelyn', 0.00012297097884899163),
 ('made', 0.000983767830791933),
 ('today', 0.0004918839153959665),
 ('paid', 0.0008607968519429415),
 ('served', 0.00012297097884899163),
 ('told', 0.0025823905558288243),
 ('.', 0.04340875553369405),
 ('lee', 0.00012297097884899163),
 ('steffi', 0.00012297097884899163),
 ('evita', 0.0004918839153959665),
 ('reached', 0.00012297097884899163),
 ('chern', 0.00012297097884899163),
 ('each', 0.0003689129365469749),
 ('rosalynn', 0.0004918839153959665),
 ('testified', 0.0003689129365469749),
 ('elena', 0.0011067388096409247),
 ('drugged', 0.00024594195769798326),
 ('says', 0.000983767830791933),
 ('isn', 0.00012297097884899163),
 ('worked', 0.00024594195769798326),
 ('lets', 0.00012297097884899163),
 ('alive', 0.00012297097884899163),
 ('madam', 0.00012297097884899163),
 ('plan', 0.0006148548942449582),
 ('chased', 0.00012297097884899163),
 ('sobbed', 0.00012297097884899163),
 ('many', 0.00012297097884899163),
 ('expressed', 0.00024594195769798326),
 ('both', 0.0003689129365469749),
 ('naked', 0.00024594195769798326),
 ('betty', 0.0003689129365469749),
 ('eimear', 0.00012297097884899163),
 ('under', 0.00024594195769798326),
 ('milene', 0.00024594195769798326),
 ('simone', 0.00012297097884899163),
 ('alexandra', 0.00012297097884899163),
 ('liao', 0.0003689129365469749),
 ('should', 0.0003689129365469749),
 ('held', 0.0006148548942449582),
 ('watched', 0.00024594195769798326),
 ('had', 0.005656665027053615),
 ('bludgeoned', 0.00024594195769798326),
 ('lara', 0.00012297097884899163),
 ('wednesday', 0.0015986227250368913),
 ('cassandra', 0.00012297097884899163),
 ('norma', 0.00012297097884899163),
 ('nana', 0.00012297097884899163),
 ('friday', 0.0006148548942449582),
 ('victoria', 0.0013526807673389081),
 ('his', 0.00012297097884899163),
 ('paula', 0.00012297097884899163),
 ('tania', 0.00012297097884899163),
 ('sue', 0.00012297097884899163),
 ('thursday', 0.0008607968519429415),
 ('admitted', 0.0003689129365469749),
 ('wanted', 0.0004918839153959665),
 ('from', 0.0025823905558288243),
 ('sounded', 0.00012297097884899163),
 ('confessed', 0.0006148548942449582),
 ('susie', 0.00024594195769798326),
 ('failed', 0.00012297097884899163),
 ('admit', 0.0003689129365469749),
 ('sen', 0.0003689129365469749),
 ('lost', 0.0003689129365469749),
 ('hosted', 0.0003689129365469749),
 ('always', 0.00012297097884899163),
 ('and', 0.15629611411706837),
 ('flew', 0.00012297097884899163),
 ('publicly', 0.00012297097884899163),
 ('saw', 0.00012297097884899163),
 ('laetitia', 0.00012297097884899163),
 ('joey', 0.00012297097884899163),
 ('karen', 0.00012297097884899163),
 ('on', 0.013034923757993113),
 ('dagmar', 0.0003689129365469749),
 ('-', 0.0022134776192818495),
 ('founded', 0.00012297097884899163),
 ('sarah', 0.0012297097884899164),
 ('brought', 0.00024594195769798326),
 ('naina', 0.0012297097884899164),
 ('blazes', 0.00012297097884899163),
 ('is', 0.007870142646335464),
 ('hilda', 0.00012297097884899163),
 ('plummeting', 0.00012297097884899163),
 ('hijacked', 0.000983767830791933),
 ('has', 0.005656665027053615),
 ('three', 0.00024594195769798326),
 ('kristin', 0.00024594195769798326),
 ('lien', 0.00012297097884899163),
 ('jeanne', 0.00024594195769798326),
 ('installed', 0.00012297097884899163),
 ('because', 0.001721593703885883),
 ('francine', 0.00012297097884899163),
 ('wendy', 0.00012297097884899163),
 ('earlier', 0.00024594195769798326),
 ('connie', 0.00012297097884899163),
 ('locked', 0.00012297097884899163),
 ('zhou', 0.00012297097884899163),
 ('amelita', 0.00024594195769798326),
 ('acquire', 0.00012297097884899163),
 ('sold', 0.00012297097884899163),
 ('margaret', 0.00012297097884899163),
 ('teresa', 0.00024594195769798326),
 ('be', 0.00012297097884899163),
 ('nancy', 0.0006148548942449582),
 ('heather', 0.0007378258730939498),
 ('raise', 0.00012297097884899163),
 ('shania', 0.00012297097884899163),
 ('when', 0.0008607968519429415),
 ('goes', 0.00012297097884899163),
 ('six', 0.0004918839153959665),
 ('seriously', 0.0014756517461878996),
 ('escaped', 0.0003689129365469749),
 ('prompted', 0.00012297097884899163),
 ('upstairs', 0.00012297097884899163),
 ('strenuously', 0.00024594195769798326),
 ('dying', 0.00024594195769798326),
 ('battered', 0.00012297097884899163),
 ('at', 0.0076242006886374815),
 ('vera', 0.0003689129365469749),
 ('maya', 0.00012297097884899163),
 ('named', 0.00012297097884899163),
 ('drove', 0.00024594195769798326),
 ('hannelore', 0.0006148548942449582),
 ('abigail', 0.00012297097884899163),
 ('natalya', 0.00012297097884899163),
 ('this', 0.0004918839153959665),
 ('saturday', 0.0003689129365469749),
 ('stands', 0.00012297097884899163),
 ('illegally', 0.00012297097884899163),
 ('one', 0.0007378258730939498),
 ('by', 0.005041810132808657),
 ('eugenia', 0.00012297097884899163),
 ('liza', 0.00012297097884899163),
 ('first', 0.00012297097884899163),
 ('along', 0.00012297097884899163),
 ('alongside', 0.0003689129365469749),
 ('cristiane', 0.00012297097884899163),
 ('wouldn', 0.00012297097884899163),
 ('for', 0.006271519921298574),
 ('heads', 0.00012297097884899163),
 ('accidentally', 0.00024594195769798326),
 ('acted', 0.00024594195769798326),
 ('came', 0.00012297097884899163),
 ('he', 0.000983767830791933),
 ('show', 0.00024594195769798326),
 ('say', 0.0004918839153959665),
 ('nina', 0.00012297097884899163),
 ('free', 0.0003689129365469749),
 ('cynthia', 0.00024594195769798326),
 ('simply', 0.00012297097884899163),
 ('guilty', 0.00024594195769798326),
 ('isabelle', 0.00012297097884899163),
 ('nikki', 0.00012297097884899163),
 ('celebrated', 0.00012297097884899163),
 ('dropped', 0.00012297097884899163),
 ('complained', 0.00012297097884899163),
 ('did', 0.0003689129365469749),
 ('queen', 0.0018445646827348746),
 ('nearly', 0.0004918839153959665),
 ('lynne', 0.00024594195769798326),
 ('claimed', 0.0003689129365469749),
 ('doris', 0.00012297097884899163),
 ('here', 0.0008607968519429415),
 ('contend', 0.00012297097884899163),
 ('liv', 0.00012297097884899163),
 ('adua', 0.00012297097884899163),
 ('talked', 0.00012297097884899163),
 ('noticed', 0.00012297097884899163),
 ('graca', 0.00024594195769798326),
 ('jenny', 0.00012297097884899163),
 ('ellen', 0.00012297097884899163),
 ('janet', 0.00012297097884899163),
 ('were', 0.017830791933103787),
 ('camilla', 0.009468765371372355),
 ('into', 0.0008607968519429415),
 ('last', 0.0014756517461878996),
 ('said', 0.0411952779144122),
 ('apparently', 0.00012297097884899163),
 ('shook', 0.0003689129365469749),
 ('ever', 0.00024594195769798326),
 ('reportedly', 0.00024594195769798326),
 ('live', 0.00024594195769798326),
 ('bonny', 0.00024594195769798326),
 ('cecilia', 0.002459419576979833),
 ('marched', 0.00012297097884899163),
 ('sleep', 0.00024594195769798326),
 ('toured', 0.00012297097884899163),
 ('stayed', 0.00012297097884899163),
 ('rania', 0.00012297097884899163),
 ('unless', 0.00012297097884899163),
 ('plead', 0.0003689129365469749),
 ('learned', 0.00012297097884899163),
 ('yu', 0.00012297097884899163),
 ('remained', 0.00024594195769798326),
 ('exploded', 0.00012297097884899163),
 ('hardly', 0.00012297097884899163),
 ('usually', 0.00024594195769798326),
 ('murdered', 0.0004918839153959665),
 ('through', 0.0008607968519429415),
 ('got', 0.0007378258730939498),
 ('with', 0.006271519921298574),
 ("'", 0.06751106738809641),
 ('early', 0.00012297097884899163),
 ('elizabeth', 0.0006148548942449582),
 ('winnie', 0.00012297097884899163),
 ('based', 0.00012297097884899163),
 ('enough', 0.00012297097884899163),
 ('lived', 0.00024594195769798326),
 ('susana', 0.00012297097884899163),
 ('polly', 0.00012297097884899163),
 ('irena', 0.00012297097884899163),
 ('to', 0.019921298573536646),
 ('lay', 0.00024594195769798326),
 ('chou', 0.00012297097884899163),
 (',', 0.21827348745696015),
 ('woke', 0.00012297097884899163),
 ('departed', 0.00012297097884899163),
 ('carolyn', 0.0004918839153959665),
 ('slain', 0.00012297097884899163),
 ('are', 0.009222823413674372),
 ('millionaires', 0.00012297097884899163),
 ('caroline', 0.00024594195769798326),
 ('dealt', 0.00012297097884899163),
 ('lisa', 0.00024594195769798326),
 ('athina', 0.00012297097884899163),
 ('annette', 0.00012297097884899163),
 ('azza', 0.00024594195769798326),
 ('tuesday', 0.00012297097884899163),
 ('the', 0.0003689129365469749),
 ('barely', 0.00012297097884899163),
 ('beside', 0.00012297097884899163),
 ('gets', 0.00012297097884899163),
 ('charged', 0.00012297097884899163),
 ('started', 0.0003689129365469749),
 ('petitioned', 0.00012297097884899163),
 ('that', 0.002090506640432858),
 ('may', 0.0006148548942449582),
 ('carol', 0.00012297097884899163),
 ('use', 0.00012297097884899163),
 ('gertrud', 0.00012297097884899163),
 ('organized', 0.00012297097884899163),
 ('suggested', 0.00012297097884899163),
 ('met', 0.0006148548942449582),
 ('donated', 0.00012297097884899163),
 ('shirley', 0.00012297097884899163),
 ('lao', 0.0008607968519429415),
 ('recover', 0.00012297097884899163),
 ('cindy', 0.0003689129365469749),
 ('insisted', 0.0004918839153959665),
 ('jerry', 0.0003689129365469749),
 ('edna', 0.00012297097884899163),
 ('visited', 0.000983767830791933),
 ('sheryl', 0.00012297097884899163),
 ('died', 0.002459419576979833),
 ('posed', 0.00012297097884899163),
 ('as', 0.008853910477127398),
 ('trapped', 0.00024594195769798326),
 ('janette', 0.00012297097884899163),
 ('henriette', 0.00012297097884899163),
 ('fast', 0.00012297097884899163),
 ('does', 0.00012297097884899163),
 ('must', 0.00024594195769798326),
 ('operated', 0.00024594195769798326),
 ('divorced', 0.00012297097884899163),
 ('returned', 0.000983767830791933),
 ('jennifer', 0.0003689129365469749),
 ('in', 0.030373831775700934),
 ('imprisoned', 0.0003689129365469749),
 ('received', 0.0006148548942449582),
 ('confiscated', 0.00012297097884899163),
 ('shot', 0.0003689129365469749),
 ('than', 0.00012297097884899163),
 ('rosalyn', 0.00012297097884899163),
 ('collecting', 0.00012297097884899163),
 ('ieng', 0.00012297097884899163),
 ('accepting', 0.00012297097884899163),
 ('accepted', 0.00012297097884899163),
 ('monica', 0.00012297097884899163),
 ('fell', 0.00012297097884899163),
 ('beatrice', 0.00024594195769798326),
 ('might', 0.0006148548942449582),
 ('run', 0.00012297097884899163),
 ('surrendered', 0.00024594195769798326),
 ('was', 0.020659124446630595),
 ('jokes', 0.00012297097884899163),
 ('cried', 0.00012297097884899163),
 ('claudia', 0.0004918839153959665),
 ('not', 0.00024594195769798326),
 ('helen', 0.00012297097884899163),
 ('out', 0.000983767830791933),
 ('perform', 0.0003689129365469749),
 ('until', 0.0004918839153959665),
 ('pojaman', 0.0011067388096409247),
 ('remitted', 0.00012297097884899163),
 ('fear', 0.00012297097884899163),
 ('jamila', 0.00012297097884899163),
 ('jeannie', 0.00012297097884899163),
 ('joined', 0.00024594195769798326),
 ('wore', 0.00024594195769798326),
 ('committed', 0.00012297097884899163),
 ('susan', 0.0007378258730939498),
 ('isabel', 0.00024594195769798326),
 ('posted', 0.00012297097884899163),
 ('sat', 0.00012297097884899163),
 ('diana', 0.0004918839153959665),
 ('marianne', 0.00012297097884899163),
 ('sofia', 0.0004918839153959665),
 ('liz', 0.00012297097884899163),
 ('launder', 0.0004918839153959665),
 ('telling', 0.00012297097884899163),
 ('samantha', 0.00024594195769798326),
 ('itching', 0.00012297097884899163),
 ('arrested', 0.00012297097884899163),
 ('regularly', 0.00012297097884899163),
 ('unwittingly', 0.0004918839153959665),
 ('announced', 0.0014756517461878996),
 ('killed', 0.002336448598130841),
 ('declared', 0.00024594195769798326),
 ('raisa', 0.0003689129365469749),
 ('washed', 0.00012297097884899163),
 ('bought', 0.00024594195769798326),
 ('comes', 0.00012297097884899163),
 ('near', 0.0007378258730939498),
 ('read', 0.00024594195769798326),
 ('evi', 0.0007378258730939498),
 ('took', 0.0008607968519429415),
 ('suzanne', 0.00012297097884899163),
 ('linda', 0.0006148548942449582),
 ('pamela', 0.00024594195769798326),
 ('never', 0.00012297097884899163),
 ('turned', 0.00012297097884899163),
 ('look', 0.00024594195769798326),
 ('broke', 0.00024594195769798326),
 ('dr', 0.00012297097884899163),
 ('khunying', 0.00024594195769798326),
 ('suffering', 0.00012297097884899163),
 ('mette', 0.00024594195769798326),
 ('shortly', 0.0006148548942449582),
 ('vanessa', 0.00012297097884899163),
 ('wang', 0.0011067388096409247),
 ('blamed', 0.00012297097884899163),
 ('win', 0.00024594195769798326),
 ('released', 0.00012297097884899163),
 ('even', 0.0004918839153959665),
 ('carla', 0.002336448598130841),
 ('suffered', 0.00024594195769798326),
 ('following', 0.00024594195769798326),
 ('botched', 0.00024594195769798326),
 ('ye', 0.00012297097884899163),
 ('earned', 0.00024594195769798326),
 ('before', 0.001967535661583866),
 ('dead', 0.000983767830791933),
 ('fled', 0.00024594195769798326),
 ('wowed', 0.00012297097884899163),
 ('esther', 0.00012297097884899163),
 ('sought', 0.00012297097884899163),
 ('iris', 0.00012297097884899163),
 ('can', 0.0014756517461878996),
 ('anne', 0.00024594195769798326),
 ('annika', 0.00012297097884899163),
 ('dorothy', 0.00012297097884899163),
 ('nicole', 0.0004918839153959665),
 ('could', 0.0003689129365469749),
 ('face', 0.00012297097884899163),
 ('unconscious', 0.00012297097884899163),
 ('ride', 0.00024594195769798326),
 ('marilyn', 0.00012297097884899163),
 ('lent', 0.0003689129365469749),
 ('winning', 0.00012297097884899163),
 ('move', 0.00012297097884899163),
 ('who', 0.004426955238563699),
 ('dina', 0.00012297097884899163),
 ('campaign', 0.00024594195769798326),
 ('used', 0.0012297097884899164),
 ('appeared', 0.0003689129365469749),
 ('stood', 0.00024594195769798326),
 ('becomes', 0.0003689129365469749),
 ('lightly', 0.00012297097884899163),
 ('mildred', 0.00012297097884899163),
 ('sheri', 0.00012297097884899163),
 ('severed', 0.00012297097884899163),
 ('every', 0.00012297097884899163),
 ('die', 0.00012297097884899163),
 ('jackie', 0.00024594195769798326),
 ('whose', 0.00024594195769798326),
 ('jill', 0.00024594195769798326),
 ('attempted', 0.00012297097884899163),
 ('renewed', 0.00024594195769798326),
 ('lila', 0.00024594195769798326),
 ('leah', 0.00024594195769798326),
 ('jeannine', 0.00012297097884899163),
 ('asma', 0.00012297097884899163),
 ('eight', 0.0003689129365469749),
 ('pledged', 0.00012297097884899163),
 ('need', 0.00012297097884899163),
 ('remain', 0.00024594195769798326),
 ('testify', 0.00012297097884899163),
 ('irina', 0.00024594195769798326),
 ('after', 0.006271519921298574),
 ('summoned', 0.00012297097884899163),
 ('spent', 0.0003689129365469749),
 ('reveal', 0.00012297097884899163),
 ('collected', 0.00012297097884899163),
 ('norodom', 0.0004918839153959665),
 ('margarita', 0.00012297097884899163),
 ('thoroughly', 0.00012297097884899163),
 ('almost', 0.0003689129365469749),
 ('won', 0.00012297097884899163),
 ('prepares', 0.00012297097884899163),
 ('gill', 0.0006148548942449582),
 ('packed', 0.00012297097884899163),
 ('sparked', 0.0003689129365469749),
 ('siti', 0.0006148548942449582),
 ('return', 0.00012297097884899163),
 ('lori', 0.0003689129365469749),
 ('sees', 0.00012297097884899163),
 ('stared', 0.0003689129365469749),
 ('ablaze', 0.00012297097884899163),
 ('jemima', 0.00024594195769798326),
 ('lita', 0.00012297097884899163),
 ('lyudmila', 0.0004918839153959665),
 ('liu', 0.0003689129365469749),
 ('cathy', 0.00012297097884899163),
 ('demanded', 0.00012297097884899163),
 ('lu', 0.00012297097884899163),
 ('olivia', 0.00012297097884899163),
 ('melinda', 0.0004918839153959665),
 ('nicoletta', 0.00012297097884899163),
 ('concluded', 0.00012297097884899163),
 ('jo', 0.00012297097884899163),
 ('hostage', 0.0008607968519429415),
 ('while', 0.0031972454500737825),
 ('frozen', 0.0003689129365469749),
 ('coleen', 0.00012297097884899163),
 ('maria', 0.002459419576979833),
 ('chopped', 0.00012297097884899163),
 ('spoke', 0.00012297097884899163),
 ('have', 0.015125430398425972),
 ('brittany', 0.00012297097884899163),
 ('asked', 0.0003689129365469749),
 ('zoe', 0.00012297097884899163),
 ('also', 0.00012297097884899163),
 ('rabri', 0.00024594195769798326),
 ('struck', 0.00012297097884899163),
 ('recalled', 0.00012297097884899163),
 ('daphne', 0.00012297097884899163),
 ('walked', 0.00012297097884899163),
 ('christina', 0.00024594195769798326),
 ('considers', 0.00012297097884899163),
 ('kissed', 0.00012297097884899163),
 ('down', 0.00012297097884899163),
 ('of', 0.016109198229217903),
 ('chow', 0.0004918839153959665),
 ('christiane', 0.00024594195769798326),
 ('keep', 0.00024594195769798326),
 ('headed', 0.00024594195769798326),
 ('more', 0.000983767830791933),

In [4]:
for key in lookup:
    lookup[key].sort(key=lambda x: x[1], reverse=True)

In [6]:
import pickle

with open("trigram_model.pkl", "wb") as f:
    pickle.dump(lookup, f)

In [43]:
import pandas as pd
from openai import OpenAI
import re
from huggingface_hub import InferenceClient
from dotenv import load_dotenv
load_dotenv()
import os
from transformers import pipeline

In [ ]:
MODEL = "openai-community/gpt2"

# Load GPT-2 locally
generator = pipeline(
    "text-generation",
    model=MODEL,
    tokenizer=MODEL,
)

# Load dataset
df = pd.read_csv("dev_set.csv")

MAX_ROWS = 1000
df = df.iloc[:MAX_ROWS]

correct = 0
predictions = []

total = len(df)

for i, (_, row) in enumerate(df.iterrows(), start=1):

    # Use only the context as the prompt
    prompt = row["context"]

    response = generator(
        prompt,
        max_new_tokens=1,            # predict the next token
        do_sample=False,             # greedy decoding
        return_full_text=False,
        pad_token_id=generator.tokenizer.eos_token_id,
    )

    generated_text = response[0]["generated_text"].strip()

    print("========== RAW ==========")
    print(generated_text)
    print("=========================")

    # Extract the first generated word
    match = re.search(r"[\w'-]+", generated_text.lower())
    prediction = match.group(0) if match else "[UNK]"

    target = str(row["answer"]).strip().lower()

    is_correct = prediction == target
    correct += is_correct

    predictions.append({
        "context": row["context"],
        "target": target,
        "prediction": prediction,
        "correct": is_correct,
    })

    print(f"{i}/{total}")
    print(f"Target: {target}")
    print(f"Pred:   {prediction}")

accuracy = correct / total

print("=" * 50)
print(f"Accuracy: {accuracy:.4%} ({correct}/{total})")

pd.DataFrame(predictions).to_csv("predictions.csv", index=False)

Device set to use mps:0

========== RAW ==========
year
=========================
1/1000
Target: day
Pred:   year
========== RAW ==========
the
=========================
2/1000
Target: the
Pred:   the
========== RAW ==========
.
=========================
3/1000
Target: morning
Pred:   [UNK]
========== RAW ==========
was
=========================
4/1000
Target: was
Pred:   was
========== RAW ==========
to
=========================
5/1000
Target: to
Pred:   to
========== RAW ==========
the
=========================
6/1000
Target: a
Pred:   the
========== RAW ==========
Bel
=========================
7/1000
Target: moscow
Pred:   bel
========== RAW ==========
that
=========================
8/1000
Target: that
Pred:   that
========== RAW ==========
of
=========================
9/1000
Target: of
Pred:   of
========== RAW ==========
parties
=========================
10/1000
Target: women
Pred:   parties
========== RAW ==========
100
=========================
11/1000
Target: 11
Pred:   100
========== RAW ==========
and
=========================
12/1000
Target: ,
Pred:   and
========== RAW ==========
.
=========================
13/1000
Target: ,
Pred:   [UNK]
========== RAW ==========
of
=========================
14/1000
Target: tonnes
Pred:   of
========== RAW ==========
the
=========================
15/1000
Target: his
Pred:   the
========== RAW ==========
commerce
=========================
16/1000
Target: deputies
Pred:   commerce
========== RAW ==========
performances
=========================
17/1000
Target: shows
Pred:   performances
========== RAW ==========
st
=========================
18/1000
Target: kilometers
Pred:   st
========== RAW ==========
the
=========================
19/1000
Target: palestinian
Pred:   the
========== RAW ==========
v
=========================
20/1000
Target: vests
Pred:   v
========== RAW ==========
the
=========================
21/1000
Target: the
Pred:   the
========== RAW ==========
after
=========================
22/1000
Target: internationals
Pred:   after
========== RAW ==========
them
=========================
23/1000
Target: relatives
Pred:   them
========== RAW ==========
cup
=========================
24/1000
Target: cup
Pred:   cup
========== RAW ==========
.
=========================
25/1000
Target: for
Pred:   [UNK]
========== RAW ==========
moment
=========================
26/1000
Target: american
Pred:   moment
========== RAW ==========
Sky
=========================
27/1000
Target: licenses
Pred:   sky
========== RAW ==========
did
=========================
28/1000
Target: battered
Pred:   did
========== RAW ==========
.
=========================
29/1000
Target: ,
Pred:   [UNK]
========== RAW ==========
the
=========================
30/1000
Target: a
Pred:   the
========== RAW ==========
boost
=========================
31/1000
Target: encourage
Pred:   boost
========== RAW ==========
there
=========================
32/1000
Target: turning
Pred:   there
========== RAW ==========
to
=========================
33/1000
Target: and
Pred:   to
========== RAW ==========
shares
=========================
34/1000
Target: u
Pred:   shares
========== RAW ==========
but
=========================
35/1000
Target: the
Pred:   but
========== RAW ==========
man
=========================
36/1000
Target: teen
Pred:   man
========== RAW ==========
damaging
=========================
37/1000
Target: causing
Pred:   damaging
========== RAW ==========
that
=========================
38/1000
Target: that
Pred:   that
========== RAW ==========
.
=========================
39/1000
Target: of
Pred:   [UNK]
========== RAW ==========
fish
=========================
40/1000
Target: uk
Pred:   fish
========== RAW ==========
dead
=========================
41/1000
Target: of
Pred:   dead
========== RAW ==========
inter
=========================
42/1000
Target: [unk]
Pred:   inter
========== RAW ==========
Prophet
=========================
43/1000
Target: united
Pred:   prophet
========== RAW ==========
the
=========================
44/1000
Target: the
Pred:   the
========== RAW ==========
the
=========================
45/1000
Target: lrb
Pred:   the
========== RAW ==========
little
=========================
46/1000
Target: 1111
Pred:   little
========== RAW ==========
the
=========================
47/1000
Target: minister
Pred:   the
========== RAW ==========

=========================
48/1000
Target: s
Pred:   [UNK]
========== RAW ==========
,
=========================
49/1000
Target: mtu
Pred:   [UNK]
========== RAW ==========
U
=========================
50/1000
Target: longshoremen
Pred:   u
========== RAW ==========
the
=========================
51/1000
Target: the
Pred:   the
========== RAW ==========
.
=========================
52/1000
Target: ,
Pred:   [UNK]
========== RAW ==========
on
=========================
53/1000
Target: and
Pred:   on
========== RAW ==========
person
=========================
54/1000
Target: iraqi
Pred:   person
========== RAW ==========
such
=========================
55/1000
Target: uncovered
Pred:   such
========== RAW ==========
on
=========================
56/1000
Target: from
Pred:   on
========== RAW ==========
of
=========================
57/1000
Target: the
Pred:   of
========== RAW ==========
net
=========================
58/1000
Target: profit
Pred:   net
========== RAW ==========
.
=========================
59/1000
Target: bank
Pred:   [UNK]
========== RAW ==========
very
=========================
60/1000
Target: anyone
Pred:   very
========== RAW ==========
security
=========================
61/1000
Target: security
Pred:   security
========== RAW ==========
that
=========================
62/1000
Target: for
Pred:   that
========== RAW ==========
have
=========================
63/1000
Target: behind
Pred:   have
========== RAW ==========
case
=========================
64/1000
Target: construction
Pred:   case
========== RAW ==========
shares
=========================
65/1000
Target: trade
Pred:   shares
========== RAW ==========
with
=========================
66/1000
Target: for
Pred:   with
========== RAW ==========
which
=========================
67/1000
Target: and
Pred:   which
========== RAW ==========
to
=========================
68/1000
Target: to
Pred:   to
========== RAW ==========

=========================
69/1000
Target: cease
Pred:   [UNK]
========== RAW ==========
.
=========================
70/1000
Target: forced
Pred:   [UNK]
========== RAW ==========
for
=========================
71/1000
Target: arrests
Pred:   for
========== RAW ==========
the
=========================
72/1000
Target: the
Pred:   the
========== RAW ==========
the
=========================
73/1000
Target: the
Pred:   the
========== RAW ==========
improving
=========================
74/1000
Target: strengthening
Pred:   improving
========== RAW ==========
.
=========================
75/1000
Target: in
Pred:   [UNK]
========== RAW ==========
long
=========================
76/1000
Target: medium
Pred:   long
========== RAW ==========
damage
=========================
77/1000
Target: casualties
Pred:   damage
========== RAW ==========
of
=========================
78/1000
Target: athens
Pred:   of
========== RAW ==========
that
=========================
79/1000
Target: benefiting
Pred:   that
========== RAW ==========
in
=========================
80/1000
Target: -
Pred:   in
========== RAW ==========
one
=========================
81/1000
Target: 11
Pred:   one
========== RAW ==========

=========================
82/1000
Target: s
Pred:   [UNK]
========== RAW ==========
-
=========================
83/1000
Target: -
Pred:   -
========== RAW ==========
2011
=========================
84/1000
Target: 1111
Pred:   2011
========== RAW ==========
with
=========================
85/1000
Target: the
Pred:   with
========== RAW ==========
the
=========================
86/1000
Target: a
Pred:   the
========== RAW ==========
first
=========================
87/1000
Target: party
Pred:   first
========== RAW ==========
arrested
=========================
88/1000
Target: demanded
Pred:   arrested
========== RAW ==========
the
=========================
89/1000
Target: large
Pred:   the
========== RAW ==========
Sunday
=========================
90/1000
Target: -
Pred:   sunday
========== RAW ==========
discovered
=========================
91/1000
Target: hasn
Pred:   discovered
========== RAW ==========
replace
=========================
92/1000
Target: reprise
Pred:   replace
========== RAW ==========
building
=========================
93/1000
Target: military
Pred:   building
========== RAW ==========
.
=========================
94/1000
Target: sunday
Pred:   [UNK]
========== RAW ==========
is
=========================
95/1000
Target: needs
Pred:   is
========== RAW ==========
the
=========================
96/1000
Target: a
Pred:   the
========== RAW ==========
car
=========================
97/1000
Target: auto
Pred:   car
========== RAW ==========
's
=========================
98/1000
Target: '
Pred:   's
========== RAW ==========
about
=========================
99/1000
Target: communism
Pred:   about
========== RAW ==========
on
=========================
100/1000
Target: on
Pred:   on
========== RAW ==========
-
=========================
101/1000
Target: -
Pred:   -
========== RAW ==========
to
=========================
102/1000
Target: to
Pred:   to
========== RAW ==========
country
=========================
103/1000
Target: republic
Pred:   country
========== RAW ==========
be
=========================
104/1000
Target: power
Pred:   be
========== RAW ==========
.
=========================
105/1000
Target: ,
Pred:   [UNK]
========== RAW ==========
weapons
=========================
106/1000
Target: weapons
Pred:   weapons
========== RAW ==========
's
=========================
107/1000
Target: '
Pred:   's
========== RAW ==========
committee
=========================
108/1000
Target: ruling
Pred:   committee
========== RAW ==========
according
=========================
109/1000
Target: the
Pred:   according
========== RAW ==========
changing
=========================
110/1000
Target: making
Pred:   changing
========== RAW ==========
is
=========================
111/1000
Target: is
Pred:   is
========== RAW ==========
.
=========================
112/1000
Target: if
Pred:   [UNK]
========== RAW ==========
the
=========================
113/1000
Target: boxing
Pred:   the
========== RAW ==========
to
=========================
114/1000
Target: to
Pred:   to
========== RAW ==========
opposition
=========================
115/1000
Target: democracy
Pred:   opposition
========== RAW ==========
to
=========================
116/1000
Target: to
Pred:   to
========== RAW ==========
new
=========================
117/1000
Target: new
Pred:   new
========== RAW ==========
that
=========================
118/1000
Target: new
Pred:   that
========== RAW ==========
of
=========================
119/1000
Target: of
Pred:   of
========== RAW ==========
said
=========================
120/1000
Target: tass
Pred:   said
========== RAW ==========
called
=========================
121/1000
Target: called
Pred:   called
========== RAW ==========
club
=========================
122/1000
Target: new
Pred:   club
========== RAW ==========
-
=========================
123/1000
Target: world
Pred:   -
========== RAW ==========
hon
=========================
124/1000
Target: invisible
Pred:   hon
========== RAW ==========
of
=========================
125/1000
Target: of
Pred:   of
========== RAW ==========
the
=========================
126/1000
Target: the
Pred:   the
========== RAW ==========
and
=========================
127/1000
Target: leading
Pred:   and
========== RAW ==========
.
=========================
128/1000
Target: in
Pred:   [UNK]
========== RAW ==========
the
=========================
129/1000
Target: here
Pred:   the
========== RAW ==========
un
=========================
130/1000
Target: popetown
Pred:   un
========== RAW ==========
the
=========================
131/1000
Target: a
Pred:   the
========== RAW ==========
-
=========================
132/1000
Target: quarries
Pred:   -
========== RAW ==========
1
=========================
133/1000
Target: going
Pred:   1
========== RAW ==========
website
=========================
134/1000
Target: country
Pred:   website
========== RAW ==========
.
=========================
135/1000
Target: '
Pred:   [UNK]
========== RAW ==========
the
=========================
136/1000
Target: running
Pred:   the
========== RAW ==========
fire
=========================
137/1000
Target: wild
Pred:   fire
========== RAW ==========
ones
=========================
138/1000
Target: project
Pred:   ones
========== RAW ==========
11
=========================
139/1000
Target: rrb
Pred:   11
========== RAW ==========
each
=========================
140/1000
Target: running
Pred:   each
========== RAW ==========
this
=========================
141/1000
Target: this
Pred:   this
========== RAW ==========
.
=========================
142/1000
Target: -
Pred:   [UNK]
========== RAW ==========
.
=========================
143/1000
Target: strip
Pred:   [UNK]
========== RAW ==========
by
=========================
144/1000
Target: over
Pred:   by
========== RAW ==========
association
=========================
145/1000
Target: association
Pred:   association
========== RAW ==========
the
=========================
146/1000
Target: better
Pred:   the
========== RAW ==========
,
=========================
147/1000
Target: chief
Pred:   [UNK]
========== RAW ==========
their
=========================
148/1000
Target: their
Pred:   their
========== RAW ==========
day
=========================
149/1000
Target: day
Pred:   day
========== RAW ==========
second
=========================
150/1000
Target: place
Pred:   second
========== RAW ==========
.
=========================
151/1000
Target: uprooted
Pred:   [UNK]
========== RAW ==========
government
=========================
152/1000
Target: labor
Pred:   government
========== RAW ==========
expected
=========================
153/1000
Target: the
Pred:   expected
========== RAW ==========
which
=========================
154/1000
Target: foreign
Pred:   which
========== RAW ==========
Ara
=========================
155/1000
Target: arafat
Pred:   ara
========== RAW ==========
September
=========================
156/1000
Target: minutes
Pred:   september
========== RAW ==========
the
=========================
157/1000
Target: gold
Pred:   the
========== RAW ==========
of
=========================
158/1000
Target: of
Pred:   of
========== RAW ==========
natural
=========================
159/1000
Target: swiss
Pred:   natural
========== RAW ==========
was
=========================
160/1000
Target: finally
Pred:   was
========== RAW ==========
and
=========================
161/1000
Target: especially
Pred:   and
========== RAW ==========
the
=========================
162/1000
Target: the
Pred:   the
========== RAW ==========
being
=========================
163/1000
Target: defaming
Pred:   being
========== RAW ==========
and
=========================
164/1000
Target: foreign
Pred:   and
========== RAW ==========
.
=========================
165/1000
Target: and
Pred:   [UNK]
========== RAW ==========
I
=========================
166/1000
Target: it
Pred:   i
========== RAW ==========

=========================
167/1000
Target: s
Pred:   [UNK]
========== RAW ==========
.
=========================
168/1000
Target: over
Pred:   [UNK]
========== RAW ==========
in
=========================
169/1000
Target: reservoirs
Pred:   in
========== RAW ==========
and
=========================
170/1000
Target: smoky
Pred:   and
========== RAW ==========
.
=========================
171/1000
Target: in
Pred:   [UNK]
========== RAW ==========
military
=========================
172/1000
Target: marine
Pred:   military
========== RAW ==========
Saturday
=========================
173/1000
Target: saturday
Pred:   saturday
========== RAW ==========
industry
=========================
174/1000
Target: industry
Pred:   industry
========== RAW ==========
part
=========================
175/1000
Target: quickly
Pred:   part
========== RAW ==========
the
=========================
176/1000
Target: today
Pred:   the
========== RAW ==========
$
=========================
177/1000
Target: accept
Pred:   [UNK]
========== RAW ==========
-
=========================
178/1000
Target: -
Pred:   -
========== RAW ==========
from
=========================
179/1000
Target: from
Pred:   from
========== RAW ==========
in
=========================
180/1000
Target: by
Pred:   in
========== RAW ==========
ban
=========================
181/1000
Target: ban
Pred:   ban
========== RAW ==========
.
=========================
182/1000
Target: ,
Pred:   [UNK]
========== RAW ==========
of
=========================
183/1000
Target: of
Pred:   of
========== RAW ==========
lack
=========================
184/1000
Target: lackluster
Pred:   lack
========== RAW ==========
one
=========================
185/1000
Target: badly
Pred:   one
========== RAW ==========
with
=========================
186/1000
Target: with
Pred:   with
========== RAW ==========
and
=========================
187/1000
Target: terrorists
Pred:   and
========== RAW ==========
on
=========================
188/1000
Target: in
Pred:   on
========== RAW ==========
development
=========================
189/1000
Target: employment
Pred:   development
========== RAW ==========
questions
=========================
190/1000
Target: team
Pred:   questions
========== RAW ==========
China
=========================
191/1000
Target: the
Pred:   china
========== RAW ==========
the
=========================
192/1000
Target: the
Pred:   the
========== RAW ==========
of
=========================
193/1000
Target: of
Pred:   of
========== RAW ==========
irregularities
=========================
194/1000
Target: complaints
Pred:   irregularities
========== RAW ==========
'
=========================
195/1000
Target: "
Pred:   '
========== RAW ==========
on
=========================
196/1000
Target: by
Pred:   on
========== RAW ==========
study
=========================
197/1000
Target: new
Pred:   study
========== RAW ==========
left
=========================
198/1000
Target: brain
Pred:   left
========== RAW ==========
who
=========================
199/1000
Target: a
Pred:   who
========== RAW ==========
's
=========================
200/1000
Target: robert
Pred:   's
========== RAW ==========
the
=========================
201/1000
Target: connection
Pred:   the
========== RAW ==========
the
=========================
202/1000
Target: a
Pred:   the
========== RAW ==========
and
=========================
203/1000
Target: boosting
Pred:   and
========== RAW ==========
Syria
=========================
204/1000
Target: the
Pred:   syria
========== RAW ==========
ban
=========================
205/1000
Target: restrictions
Pred:   ban
========== RAW ==========
end
=========================
206/1000
Target: hungarian
Pred:   end
========== RAW ==========
m
=========================
207/1000
Target: michele
Pred:   m
========== RAW ==========
from
=========================
208/1000
Target: of
Pred:   from
========== RAW ==========
security
=========================
209/1000
Target: future
Pred:   security
========== RAW ==========
to
=========================
210/1000
Target: '
Pred:   to
========== RAW ==========
were
=========================
211/1000
Target: were
Pred:   were
========== RAW ==========
progress
=========================
212/1000
Target: progress
Pred:   progress
========== RAW ==========
after
=========================
213/1000
Target: after
Pred:   after
========== RAW ==========
been
=========================
214/1000
Target: gone
Pred:   been
========== RAW ==========
about
=========================
215/1000
Target: about
Pred:   about
========== RAW ==========
against
=========================
216/1000
Target: during
Pred:   against
========== RAW ==========
a
=========================
217/1000
Target: reached

In [ ]:
# Load masked language model
fill_mask = pipeline(
    "fill-mask",
    model="FacebookAI/roberta-large",
    tokenizer="FacebookAI/roberta-large",
    )

MASK = fill_mask.tokenizer.mask_token

# Load dataset
df = pd.read_csv("dev_set.csv")

MAX_ROWS = 1000
df = df.iloc[:MAX_ROWS]

correct = 0
predictions = []

TOP_K = 100

for i, row in df.iterrows():

    context = row["context"]
    first_letter = str(row["first letter"]).lower()
    target = str(row["answer"]).strip().lower()

    text = context + " " + MASK

    results = fill_mask(text, top_k=TOP_K)

    prediction = "[UNK]"

    for candidate in results:

        token = candidate["token_str"].strip().lower()

        if token.startswith(first_letter):
            prediction = token
            break

    is_correct = prediction == target
    correct += is_correct

    predictions.append({
        "context": context,
        "first_letter": first_letter,
        "target": target,
        "prediction": prediction,
        "correct": is_correct,
    })

    print(f"{i+1}/{len(df)}")
    print(f"Target: {target}")
    print(f"Pred:   {prediction}")
    print("✓" if is_correct else "✗")
    print()

accuracy = correct / len(df)

print("=" * 50)
print(f"Accuracy: {accuracy:.4%} ({correct}/{len(df)})")

pd.DataFrame(predictions).to_csv("predictions.csv", index=False)

Device set to use mps:0

1/1000
Target: day
Pred:   day
✓

2/1000
Target: the
Pred:   the
✓

3/1000
Target: morning
Pred:   morning
✓

4/1000
Target: was
Pred:   was
✓

5/1000
Target: to
Pred:   to
✓

6/1000
Target: a
Pred:   afghanistan
✗

7/1000
Target: moscow
Pred:   moscow
✓

8/1000
Target: that
Pred:   to
✗

9/1000
Target: of
Pred:   of
✓

10/1000
Target: women
Pred:   women
✓

11/1000
Target: 11
Pred:   15
✗

12/1000
Target: ,
Pred:   ,
✓

13/1000
Target: ,
Pred:   ,
✓

14/1000
Target: tonnes
Pred:   tuna
✗

15/1000
Target: his
Pred:   him
✗

16/1000
Target: deputies
Pred:   deputies
✓

17/1000
Target: shows
Pred:   shows
✓

18/1000
Target: kilometers
Pred:   km
✗

19/1000
Target: palestinian
Pred:   palestinians
✗

20/1000
Target: vests
Pred:   vest
✗

21/1000
Target: the
Pred:   trouble
✗

22/1000
Target: internationals
Pred:   international
✗

23/1000
Target: relatives
Pred:   relatives
✓

24/1000
Target: cup
Pred:   cup
✓

25/1000
Target: for
Pred:   for
✓

26/1000
Target: american
Pred:   airport
✗

27/1000
Target: licenses
Pred:   licences
✗

28/1000
Target: battered
Pred:   became
✗

29/1000
Target: ,
Pred:   ,
✓

30/1000
Target: a
Pred:   a
✓

31/1000
Target: encourage
Pred:   encourage
✓

32/1000
Target: turning
Pred:   thrilled
✗

33/1000
Target: and
Pred:   and
✓

34/1000
Target: u
Pred:   underlying
✗

35/1000
Target: the
Pred:   the
✓

36/1000
Target: teen
Pred:   teen
✓

37/1000
Target: causing
Pred:   crops
✗

38/1000
Target: that
Pred:   there
✗

39/1000
Target: of
Pred:   of
✓

40/1000
Target: uk
Pred:   ursday
✗

41/1000
Target: of
Pred:   of
✓

42/1000
Target: [unk]
Pred:   […]
✗

43/1000
Target: united
Pred:   un
✗

44/1000
Target: the
Pred:   the
✓

45/1000
Target: lrb
Pred:   latest
✗

46/1000
Target: 1111
Pred:   [UNK]
✗

47/1000
Target: minister
Pred:   mr
✗

48/1000
Target: s
Pred:   s
✓

49/1000
Target: mtu
Pred:   man
✗

50/1000
Target: longshoremen
Pred:   labor
✗

51/1000
Target: the
Pred:   the
✓

52/1000
Target: ,
Pred:   ,
✓

53/1000
Target: and
Pred:   and
✓

54/1000
Target: iraqi
Pred:   iraqi
✓

55/1000
Target: uncovered
Pred:   u
✗

56/1000
Target: from
Pred:   from
✓

57/1000
Target: the
Pred:   the
✓

58/1000
Target: profit
Pred:   profit
✓

59/1000
Target: bank
Pred:   bank
✓

60/1000
Target: anyone
Pred:   a
✗

61/1000
Target: security
Pred:   security
✓

62/1000
Target: for
Pred:   fines
✗

63/1000
Target: behind
Pred:   bombed
✗

64/1000
Target: construction
Pred:   company
✗

65/1000
Target: trade
Pred:   turnover
✗

66/1000
Target: for
Pred:   for
✓

67/1000
Target: and
Pred:   and
✓

68/1000
Target: to
Pred:   to
✓

69/1000
Target: cease
Pred:   c
✗

70/1000
Target: forced
Pred:   for
✗

71/1000
Target: arrests
Pred:   a
✗

72/1000
Target: the
Pred:   the
✓

73/1000
Target: the
Pred:   the
✓

74/1000
Target: strengthening
Pred:   strengthening
✓

75/1000
Target: in
Pred:   in
✓

76/1000
Target: medium
Pred:   mortgages
✗

77/1000
Target: casualties
Pred:   casualties
✓

78/1000
Target: athens
Pred:   a
✗

79/1000
Target: benefiting
Pred:   by
✗

80/1000
Target: -
Pred:   -
✓

81/1000
Target: 11
Pred:   15
✗

82/1000
Target: s
Pred:   s
✓

83/1000
Target: -
Pred:   -
✓

84/1000
Target: 1111
Pred:   1999
✗

85/1000
Target: the
Pred:   today
✗

86/1000
Target: a
Pred:   a
✓

87/1000
Target: party
Pred:   party
✓

88/1000
Target: demanded
Pred:   disappeared
✗

89/1000
Target: large
Pred:   losses
✗

90/1000
Target: -
Pred:   -
✓

91/1000
Target: hasn
Pred:   has
✗

92/1000
Target: reprise
Pred:   run
✗

93/1000
Target: military
Pred:   mall
✗

94/1000
Target: sunday
Pred:   sunday
✓

95/1000
Target: needs
Pred:   needs
✓

96/1000
Target: a
Pred:   a
✓

97/1000
Target: auto
Pred:   auto
✓

98/1000
Target: '
Pred:   's
✗

99/1000
Target: communism
Pred:   close
✗

100/1000
Target: on
Pred:   on
✓

101/1000
Target: -
Pred:   -
✓

102/1000
Target: to
Pred:   to
✓

103/1000
Target: republic
Pred:   rebellion
✗

104/1000
Target: power
Pred:   provide
✗

105/1000
Target: ,
Pred:   ,
✓

106/1000
Target: weapons
Pred:   weapons
✓

107/1000
Target: '
Pred:   's
✗

108/1000
Target: ruling
Pred:   ruling
✓

109/1000
Target: the
Pred:   the
✓

110/1000
Target: making
Pred:   moving
✗

111/1000
Target: is
Pred:   is
✓

112/1000
Target: if
Pred:   in
✗

113/1000
Target: boxing
Pred:   business
✗

114/1000
Target: to
Pred:   to
✓

115/1000
Target: democracy
Pred:   democratic
✗

116/1000
Target: to
Pred:   to
✓

117/1000
Target: new
Pred:   new
✓

118/1000
Target: new
Pred:   nigeria
✗

119/1000
Target: of
Pred:   of
✓

120/1000
Target: tass
Pred:   tweeted
✗

121/1000
Target: called
Pred:   called
✓

122/1000
Target: new
Pred:   nhl
✗

123/1000
Target: world
Pred:   website
✗

124/1000
Target: invisible
Pred:   icon
✗

125/1000
Target: of
Pred:   of
✓

126/1000
Target: the
Pred:   the
✓

127/1000
Target: leading
Pred:   l
✗

128/1000
Target: in
Pred:   in
✓

129/1000
Target: here
Pred:   him
✗

130/1000
Target: popetown
Pred:   p
✗

131/1000
Target: a
Pred:   april
✗

132/1000
Target: quarries
Pred:   [UNK]
✗

133/1000
Target: going
Pred:   going
✓

134/1000
Target: country
Pred:   country
✓

135/1000
Target: '
Pred:   '
✓

136/1000
Target: running
Pred:   runner
✗

137/1000
Target: wild
Pred:   wildfire
✗

138/1000
Target: project
Pred:   pc
✗

139/1000
Target: rrb
Pred:   r
✗

140/1000
Target: running
Pred:   r
✗

141/1000
Target: this
Pred:   today
✗

142/1000
Target: -
Pred:   [UNK]
✗

143/1000
Target: strip
Pred:   suburb
✗

144/1000
Target: over
Pred:   over
✓

145/1000
Target: association
Pred:   association
✓

146/1000
Target: better
Pred:   benefits
✗

147/1000
Target: chief
Pred:   cabinet
✗

148/1000
Target: their
Pred:   their
✓

149/1000
Target: day
Pred:   day
✓

150/1000
Target: place
Pred:   preliminary
✗

151/1000
Target: uprooted
Pred:   [UNK]
✗

152/1000
Target: labor
Pred:   leadership
✗

153/1000
Target: the
Pred:   the
✓

154/1000
Target: foreign
Pred:   friday
✗

155/1000
Target: arafat
Pred:   adam
✗

156/1000
Target: minutes
Pred:   may
✗

157/1000
Target: gold
Pred:   gold
✓

158/1000
Target: of
Pred:   of
✓

159/1000
Target: swiss
Pred:   status
✗

160/1000
Target: finally
Pred:   from
✗

161/1000
Target: especially
Pred:   especially
✓

162/1000
Target: the
Pred:   the
✓

163/1000
Target: defaming
Pred:   death
✗

164/1000
Target: foreign
Pred:   [UNK]
✗

165/1000
Target: and
Pred:   and
✓

166/1000
Target: it
Pred:   i
✗

167/1000
Target: s
Pred:   s
✓

168/1000
Target: over
Pred:   over
✓

169/1000
Target: reservoirs
Pred:   reservoirs
✓

170/1000
Target: smoky
Pred:   smoke
✗

171/1000
Target: in
Pred:   in
✓

172/1000
Target: marine
Pred:   military
✗

173/1000
Target: saturday
Pred:   saturday
✓

174/1000
Target: industry
Pred:   industry
✓

175/1000
Target: quickly
Pred:   [UNK]
✗

176/1000
Target: today
Pred:   terrorism
✗

177/1000
Target: accept
Pred:   april
✗

178/1000
Target: -
Pred:   -
✓

179/1000
Target: from
Pred:   for
✗

180/1000
Target: by
Pred:   by
✓

181/1000
Target: ban
Pred:   ban
✓

182/1000
Target: ,
Pred:   ,
✓

183/1000
Target: of
Pred:   of
✓

184/1000
Target: lackluster
Pred:   lackluster
✓

185/1000
Target: badly
Pred:   bystanders
✗

186/1000
Target: with
Pred:   with
✓

187/1000
Target: terrorists
Pred:   terrorists
✓

188/1000
Target: in
Pred:   indefinitely
✗

189/1000
Target: employment
Pred:   employment
✓

190/1000
Target: team
Pred:   the
✗

191/1000
Target: the
Pred:   the
✓

192/1000
Target: the
Pred:   the
✓

193/1000
Target: of
Pred:   of
✓

194/1000
Target: complaints
Pred:   closures
✗

195/1000
Target: "
Pred:   ""
✗

196/1000
Target: by
Pred:   by
✓

197/1000
Target: new
Pred:   new
✓

198/1000
Target: brain
Pred:   brain
✓

199/1000
Target: a
Pred:   a
✓

200/1000
Target: robert
Pred:   role
✗

201/1000
Target: connection
Pred:   california
✗

202/1000
Target: a
Pred:   a
✓

203/1000
Target: boosting
Pred:   but
✗

204/1000
Target: the
Pred:   the
✓

205/1000
Target: restrictions
Pred:   restrictions
✓

206/1000
Target: hungarian
Pred:   hospital
✗

207/1000
Target: michele
Pred:   m
✗

208/1000
Target: of
Pred:   of
✓

209/1000
Target: future
Pred:   future
✓

210/1000
Target: '
Pred:   's
✗

211/1000
Target: were
Pred:   were
✓

212/1000
Target: progress
Pred:   progress
✓

213/1000
Target: after
Pred:   ago
✗

214/1000
Target: gone
Pred:   graduated
✗

215/1000
Target: about
Pred:   about
✓

216/1000
Target: during
Pred:   during
✓

217/1000
Target: reached
Pred:   reached
✓

218/1000
Target: session
Pred:   session
✓

219/1000
Target: of
Pred:   of
✓

220/1000
Target: injuring
Pred:   in
✗

221/1000
Target: give
Pred:   give
✓

222/1000
Target: good
Pred:   good
✓

223/1000
Target: -
Pred:   -
✓

224/1000
Target: ]
Pred:   ]
✓

225/1000
Target: at
Pred:   at
✓

226/1000
Target: first
Pred:   flight
✗

227/1000
Target: ,
Pred:   ,
✓

228/1000
Target: stronger
Pred:   security
✗

229/1000
Target: test
Pred:   test
✓

230/1000
Target: would
Pred:   would
✓

231/1000
Target: by
Pred:   by
✓

232/1000
Target: like
Pred:   like
✓

233/1000
Target: by
Pred:   by
✓

234/1000
Target: among
Pred:   a
✗

235/1000
Target: died
Pred:   died
✓

236/1000
Target: and
Pred:   and
✓

237/1000
Target: national
Pred:   negotiations
✗

238/1000
Target: man
Pred:   man
✓

239/1000
Target: s
Pred:   s
✓

240/1000
Target: by
Pred:   by
✓

241/1000
Target: an
Pred:   and
✗

242/1000
Target: losing
Pred:   limitations
✗

243/1000
Target: qaida
Pred:   qaida
✓

244/1000
Target: of
Pred:   of
✓

245/1000
Target: driving
Pred:   d
✗

246/1000
Target: s
Pred:   s
✓

247/1000
Target: students
Pred:   security
✗

248/1000
Target: for
Pred:   for
✓

249/1000
Target: after
Pred:   a
✗

250/1000
Target: thing
Pred:   thing
✓

251/1000
Target: blossomed
Pred:   be
✗

252/1000
Target: ,
Pred:   ,
✓

253/1000
Target: at
Pred:   a
✗

254/1000
Target: of
Pred:   of
✓

255/1000
Target: indo
Pred:   india
✗

256/1000
Target: taking
Pred:   the
✗

257/1000
Target: a
Pred:   and
✗

258/1000
Target: israel
Pred:   it
✗

259/1000
Target: beyond
Pred:   beyond
✓

260/1000
Target: green
Pred:   go
✗

261/1000
Target: ,
Pred:   ,
✓

262/1000
Target: days
Pred:   days
✓

263/1000
Target: books
Pred:   b
✗

264/1000
Target: for
Pred:   for
✓

265/1000
Target: the
Pred:   the
✓

266/1000
Target: and
Pred:   agency
✗

267/1000
Target: the
Pred:   the
✓

268/1000
Target: to
Pred:   to
✓

269/1000
Target: on
Pred:   on
✓

270/1000
Target: for
Pred:   for
✓

271/1000
Target: billion
Pred:   billion
✓

272/1000
Target: the
Pred:   the
✓

273/1000
Target: that
Pred:   to
✗

274/1000
Target: that
Pred:   that
✓

275/1000
Target: than
Pred:   than
✓

276/1000
Target: the
Pred:   the
✓

277/1000
Target: will
Pred:   warned
✗

278/1000
Target: ago
Pred:   ago
✓

279/1000
Target: over
Pred:   over
✓

280/1000
Target: thursday
Pred:   thursday
✓

281/1000
Target: holy
Pred:   holy
✓

282/1000
Target: of
Pred:   of
✓

283/1000
Target: chechnya
Pred:   c
✗

284/1000
Target: east
Pred:   evidence
✗

285/1000
Target: '
Pred:   's
✗

286/1000
Target: designs
Pred:   design
✗

287/1000
Target: of
Pred:   of
✓

288/1000
Target: state
Pred:   state
✓

289/1000
Target: ,
Pred:   ,
✓

290/1000
Target: and
Pred:   and
✓

291/1000
Target: immediate
Pred:   injuries
✗

292/1000
Target: ,
Pred:   ,
✓

293/1000
Target: nabil
Pred:   n
✗

294/1000
Target: commerce
Pred:   c
✗

295/1000
Target: press
Pred:   party
✗

296/1000
Target: of
Pred:   of
✓

297/1000
Target: militant
Pred:   militia
✗

298/1000
Target: -
Pred:   -
✓

299/1000
Target: '
Pred:   's
✗

300/1000
Target: nation
Pred:   negotiators
✗

301/1000
Target: net
Pred:   net
✓

302/1000
Target: was
Pred:   was
✓

303/1000
Target: a
Pred:   a
✓

304/1000
Target: to
Pred:   to
✓

305/1000
Target: -
Pred:   -
✓

306/1000
Target: and
Pred:   area
✗

307/1000
Target: used
Pred:   used
✓

308/1000
Target: human
Pred:   health
✗

309/1000
Target: a
Pred:   and
✗

310/1000
Target: ,
Pred:   ,
✓

311/1000
Target: s
Pred:   s
✓

312/1000
Target: version
Pred:   virus
✗

313/1000
Target: cranes
Pred:   chicks
✗

314/1000
Target: the
Pred:   the
✓

315/1000
Target: district
Pred:   district
✓

316/1000
Target: service
Pred:   service
✓

317/1000
Target: amend
Pred:   avoid
✗

318/1000
Target: to
Pred:   to
✓

319/1000
Target: as
Pred:   as
✓

320/1000
Target: olympic
Pred:   olympics
✗

321/1000
Target: conference
Pred:   conference
✓

322/1000
Target: ,
Pred:   ,
✓

323/1000
Target: .
Pred:   .
✓

324/1000
Target: central
Pred:   china
✗

325/1000
Target: -
Pred:   -
✓

326/1000
Target: ends
Pred:   explores
✗

327/1000
Target: men
Pred:   major
✗

328/1000
Target: in
Pred:   in
✓

329/1000
Target: markets
Pred:   markets
✓

330/1000
Target: involved
Pred:   indicted
✗

331/1000
Target: new
Pred:   [UNK]
✗

332/1000
Target: official
Pred:   official
✓

333/1000
Target: would
Pred:   war
✗

334/1000
Target: vice
Pred:   vice
✓

335/1000
Target: defend
Pred:   deliver
✗

336/1000
Target: adolescent
Pred:   attacks
✗

337/1000
Target: a
Pred:   and
✗

338/1000
Target: '
Pred:   's
✗

339/1000
Target: -
Pred:   -
✓

340/1000
Target: of
Pred:   of
✓

341/1000
Target: management
Pred:   may
✗

342/1000
Target: the
Pred:   today
✗

343/1000
Target: to
Pred:   to
✓

344/1000
Target: west
Pred:   west
✓

345/1000
Target: one
Pred:   on
✗

346/1000
Target: european
Pred:   europe
✗

347/1000
Target: the
Pred:   time
✗

348/1000
Target: ,
Pred:   ,
✓

349/1000
Target: s
Pred:   s
✓

350/1000
Target: day
Pred:   day
✓

351/1000
Target: of
Pred:   of
✓

352/1000
Target: '
Pred:   's
✗

353/1000
Target: post
Pred:   pursue
✗

354/1000
Target: rounding
Pred:   representing
✗

355/1000
Target: the
Pred:   to
✗

356/1000
Target: ,
Pred:   ,
✓

357/1000
Target: s
Pred:   s
✓

358/1000
Target: expanding
Pred:   expanding
✓

359/1000
Target: ,
Pred:   ,
✓

360/1000
Target: mir
Pred:   morning
✗

361/1000
Target: government
Pred:   government
✓

362/1000
Target: best
Pred:   best
✓

363/1000
Target: about
Pred:   about
✓

364/1000
Target: to
Pred:   to
✓

365/1000
Target: safe
Pred:   safe
✓

366/1000
Target: divert
Pred:   discredit
✗

367/1000
Target: pledged
Pred:   pakistan
✗

368/1000
Target: time
Pred:   term
✗

369/1000
Target: commitment
Pred:   cause
✗

370/1000
Target: out
Pred:   out
✓

371/1000
Target: on
Pred:   opened
✗

372/1000
Target: a
Pred:   and
✗

373/1000
Target: was
Pred:   was
✓

374/1000
Target: raise
Pred:   raise
✓

375/1000
Target: values
Pred:   values
✓

376/1000
Target: in
Pred:   in
✓

377/1000
Target: uprising
Pred:   uprising
✓

378/1000
Target: 11
Pred:   14
✗

379/1000
Target: equal
Pred:   equals
✗

380/1000
Target: should
Pred:   se
✗

381/1000
Target: danger
Pred:   danger
✓

382/1000
Target: way
Pred:   war
✗

383/1000
Target: s
Pred:   s
✓

384/1000
Target: murder
Pred:   murder
✓

385/1000
Target: at
Pred:   after
✗

386/1000
Target: .
Pred:   .
✓

387/1000
Target: steady
Pred:   surge
✗

388/1000
Target: free
Pred:   for
✗

389/1000
Target: in
Pred:   in
✓

390/1000
Target: the
Pred:   the
✓

391/1000
Target: '
Pred:   '
✓

392/1000
Target: lunched
Pred:   learned
✗

393/1000
Target: and
Pred:   and
✓

394/1000
Target: a
Pred:   analysts
✗

395/1000
Target: impose
Pred:   into
✗

396/1000
Target: .
Pred:   ...
✗

397/1000
Target: incident
Pred:   incident
✓

398/1000
Target: poking
Pred:   possible
✗

399/1000
Target: by
Pred:   by
✓

400/1000
Target: the
Pred:   turkey
✗

401/1000
Target: the
Pred:   the
✓

402/1000
Target: his
Pred:   him
✗

403/1000
Target: allowed
Pred:   attacked
✗

404/1000
Target: israeli
Pred:   israeli
✓

405/1000
Target: bombing
Pred:   bombing
✓

406/1000
Target: mexico
Pred:   more
✗

407/1000
Target: ,
Pred:   ,
✓

408/1000
Target: ,
Pred:   ,
✓

409/1000
Target: reported
Pred:   reports
✗

410/1000
Target: at
Pred:   at
✓

411/1000
Target: foreign
Pred:   forum
✗

412/1000
Target: citizens
Pred:   children
✗

413/1000
Target: the
Pred:   the
✓

414/1000
Target: drinking
Pred:   drinks
✗

415/1000
Target: two
Pred:   troops
✗

416/1000
Target: saturday
Pred:   sunday
✗

417/1000
Target: effort
Pred:   emergency
✗

418/1000
Target: quoted
Pred:   quoted
✓

419/1000
Target: terrorist
Pred:   terror
✗

420/1000
Target: ,
Pred:   ,
✓

421/1000
Target: to
Pred:   to
✓

422/1000
Target: because
Pred:   because
✓

423/1000
Target: a
Pred:   april
✗

424/1000
Target: seas
Pred:   seas
✓

425/1000
Target: to
Pred:   to
✓

426/1000
Target: nt
Pred:   [UNK]
✗

427/1000
Target: in
Pred:   in
✓

428/1000
Target: '
Pred:   's
✗

429/1000
Target: to
Pred:   to
✓

430/1000
Target: s
Pred:   s
✓

431/1000
Target: and
Pred:   and
✓

432/1000
Target: the
Pred:   the
✓

433/1000
Target: a
Pred:   anything
✗

434/1000
Target: or
Pred:   origin
✗

435/1000
Target: of
Pred:   of
✓

436/1000
Target: shown
Pred:   successful
✗

437/1000
Target: report
Pred:   report
✓

438/1000
Target: at
Pred:   at
✓

439/1000
Target: buy
Pred:   ban
✗

440/1000
Target: died
Pred:   died
✓

441/1000
Target: ended
Pred:   ended
✓

442/1000
Target: and
Pred:   and
✓

443/1000
Target: strip
Pred:   state
✗

444/1000
Target: relics
Pred:   relics
✓

445/1000
Target: rule
Pred:   reference
✗

446/1000
Target: at
Pred:   at
✓

447/1000
Target: and
Pred:   announced
✗

448/1000
Target: prize
Pred:   prize
✓

449/1000
Target: the
Pred:   them
✗

450/1000
Target: projects
Pred:   projects
✓

451/1000
Target: the
Pred:   tuesday
✗

452/1000
Target: could
Pred:   could
✓

453/1000
Target: on
Pred:   on
✓

454/1000
Target: in
Pred:   in
✓

455/1000
Target: bankruptcy
Pred:   bankruptcy
✓

456/1000
Target: in
Pred:   in
✓

457/1000
Target: for
Pred:   for
✓

458/1000
Target: and
Pred:   and
✓

459/1000
Target: of
Pred:   of
✓

460/1000
Target: 111
Pred:   100
✗

461/1000
Target: of
Pred:   of
✓

462/1000
Target: division
Pred:   department
✗

463/1000
Target: ,
Pred:   ,
✓

464/1000
Target: -
Pred:   -
✓

465/1000
Target: tourist
Pred:   taiwan
✗

466/1000
Target: inter
Pred:   iran
✗

467/1000
Target: filing
Pred:   filing
✓

468/1000
Target: at
Pred:   against
✗

469/1000
Target: the
Pred:   the
✓

470/1000
Target: '
Pred:   's
✗

471/1000
Target: swedish
Pred:   sun
✗

472/1000
Target: and
Pred:   a
✗

473/1000
Target: the
Pred:   the
✓

474/1000
Target: a
Pred:   allegations
✗

475/1000
Target: drew
Pred:   deal
✗

476/1000
Target: tourist
Pred:   tourist
✓

477/1000
Target: to
Pred:   to
✓

478/1000
Target: the
Pred:   the
✓

479/1000
Target: region
Pred:   region
✓

480/1000
Target: nurse
Pred:   nun
✗

481/1000
Target: may
Pred:   make
✗

482/1000
Target: one
Pred:   of
✗

483/1000
Target: force
Pred:   force
✓

484/1000
Target: of
Pred:   of
✓

485/1000
Target: visit
Pred:   vacation
✗

486/1000
Target: last
Pred:   losses
✗

487/1000
Target: still
Pred:   still
✓

488/1000
Target: bought
Pred:   been
✗

489/1000
Target: 111
Pred:   1
✗

490/1000
Target: leader
Pred:   latest
✗

491/1000
Target: deadlocked
Pred:   delayed
✗

492/1000
Target: hope
Pred:   handcuffs
✗

493/1000
Target: km
Pred:   kilometers
✗

494/1000
Target: monday
Pred:   monday
✓

495/1000
Target: a
Pred:   a
✓

496/1000
Target: lesley
Pred:   [UNK]
✗

497/1000
Target: s
Pred:   s
✓

498/1000
Target: possibly
Pred:   producing
✗

499/1000
Target: a
Pred:   a
✓

500/1000
Target: a
Pred:   a
✓

501/1000
Target: a
Pred:   archaeologists
✗

502/1000
Target: irna
Pred:   insisted
✗

503/1000
Target: made
Pred:   made
✓

504/1000
Target: or
Pred:   on
✗

505/1000
Target: of
Pred:   of
✓

506/1000
Target: newspaper
Pred:   news
✗

507/1000
Target: a
Pred:   and
✗

508/1000
Target: billion
Pred:   billion
✓

509/1000
Target: a
Pred:   a
✓

510/1000
Target: eastern
Pred:   eastern
✓

511/1000
Target: newspaper
Pred:   news
✗

512/1000
Target: japanese
Pred:   japanese
✓

513/1000
Target: want
Pred:   were
✗

514/1000
Target: points
Pred:   percent
✗

515/1000
Target: wellstone
Pred:   white
✗

516/1000
Target: euro
Pred:   [UNK]
✗

517/1000
Target: eritrea
Pred:   ethiopia
✗

518/1000
Target: victory
Pred:   victory
✓

519/1000
Target: rebels
Pred:   rebels
✓

520/1000
Target: for